contact/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('contact_us/',views.contact,name='contact_us'),
]

display/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('<brand>', views.shoes_list, name='shoes_list'),
    path('<brand>/<series>/<shoesname>', views.shoes_detail, name='shoes_detail'),
    path('<brand>/<brand_more>', views.brand_more, name='brand_more'),
]

index/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
]

info/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('introduce/',views.info,name='info'),
]

news/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('<num>',views.news,name='news'),
]

shoes/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    # 指向index的路由文件urls.py
    # 第一参数：urls.py文件、第二参数：一般以项目应用名称命名、第三参数：路由命名空间
    path('',include(('index.urls','index'),namespace='index')),
    path('info/',include(('info.urls','info'),namespace='info')),
    path('display/',include(('display.urls','display'),namespace='display')),
    path('news/',include(('news.urls','news'),namespace='news')),
    path('contact/',include(('contact.urls','contact'),namespace='contact')),
    path('user/',include(('user.urls','user'),namespace='user')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('publish/', views.publish, name="publish"),
    path('publish_list/', views.publish_list, name="publish_list"),
    path('publish_list/<int:product_id>', views.publish_list_detail, name="publish_list_detail"),
]

contact/models.py
from django.db import models

# Create your models here.

display/models.py
from django.db import models

# Create your models here.

index/models.py
from django.db import models

# Create your models here.

info/models.py
from django.db import models

# Create your models here.

news/models.py
from django.db import models

# Create your models here.

user/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
# 模型类
class Product(models.Model):
    # 表字段
    title = models.CharField(default="例：AJ1", max_length=50)
    intro = models.TextField(default="在这里写球鞋介绍")
    icon = models.ImageField(default="default_icon.png",upload_to='images/') 
    image = models.ImageField(default="default_image.png",upload_to='images/')
    
    votes = models.IntegerField(default=1)
    pub_date = models.DateTimeField()
    publish_user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    # 后台显示的model名称
    def __str__(self):
        return self.title

contact/views.py
from django.shortcuts import render

# Create your views here.
def contact(request):
    return render(request,'contact.html')

display/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def shoes_list(request, brand):
    return render(request, brand+'.html')


def shoes_detail(request, brand, series, shoesname):
    return render(request, shoesname+'.html')


def brand_more(request, brand, brand_more):
    return render(request, brand_more+'.html')

index/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'index.html')

info/views.py
from django.shortcuts import render

# Create your views here.
def info(request):
    return render(request,'info.html')

news/views.py
from django.shortcuts import render

# Create your views here.
def news(request,num):
    return render(request, 'news'+num+'.html')

user/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.models import User
from django.contrib import auth
from .models import Product
from django.contrib.auth.decorators import login_required
from django.utils import timezone
from django.contrib import messages


# Create your views here.
def signup(request):
    if request.method == 'GET':
        return render(request, 'signup.html')
    elif request.method == 'POST':
        user_name = request.POST['username']
        password1 = request.POST['password_initial']
        password2 = request.POST['password_confirm']
        try:
            User.objects.get(username=user_name)
            # 若用户名已存在,返回用户名已存在提示
            return render(request, 'signup.html', {'username_error':'该用户名已存在'})
        except User.DoesNotExist:
            # 若用户名不存在,判断密码是否有误
            if password1 == password2:
                User.objects.create_user(username=user_name, password=password1)
                # 重定向到另一个页面
                messages.success(request,"注册成功")
                return redirect('index:index')
            else:
                return render(request, 'signup.html', {'password_error':'您输入的密码不一致'})


def login(request):
    if request.method == 'GET':
        return render(request, 'login.html')
    elif request.method == 'POST':
        user_name = request.POST['username']
        pass_word = request.POST['password']
        user = auth.authenticate(username=user_name,password=pass_word)
        if user is None:
            return render(request, 'login.html', {'error':'您输入的用户名或密码不正确'})
        else:
            auth.login(request, user)
            messages.success(request,"登录成功")
            return redirect('index:index')


def logout(request):
    if request.method == 'POST':
        user = auth.logout(request)
        return redirect('index:index')


@login_required  # 仅当用户登录了才能跳转到此页面，哪怕直接输入/user/publish
def publish(request):
    if request.method == 'GET':
        return render(request, 'publish.html')
    elif request.method == 'POST':
        title = request.POST['shoes_title']
        intro = request.POST['shoes_introduce']
        try:    # 用户未上传图片，会报错
            icon = request.FILES['shoes_small_picture']
            image = request.FILES['shoes_big_picture']

            # 将上述用户提交的信息存放到数据库
            product = Product()
            product.title = title
            product.intro = intro
            product.icon = icon
            product.image = image
            product.pub_date = timezone.datetime.now()  # 记录用户点击发布按钮时的时间
            product.publish_user = request.user

            product.save()

            return redirect('index:index')
            
        except Exception as err:
            return render(request,'publish.html',{'picture_error':'请上传图片'})


def publish_list(request):
    products = Product.objects
    return render(request, 'publish_list.html',{'products':products})


def publish_list_detail(request, product_id):
    product = get_object_or_404(Product, pk=product_id) # 主键形式获取Product表中的对应ID
    return render(request, 'publish_list_detail.html',{'product':product})

display/templates/adidas.html
{% extends 'theme_for_shoes_list.html' %}
{% load staticfiles %}

{% block title %}<title>球鞋展示-ADIDAS</title>{% endblock title %}
{% block rotation_picture %}
	<li><img src="{% static 'img/adidas/1.png' %}" alt=""></li>
	<li><img src="{% static 'img/adidas/2.png' %}" alt=""></li>
	<li><img src="{% static 'img/adidas/3.png' %}" alt=""></li>
	<li><img src="{% static 'img/adidas/4.png' %}" alt=""></li>
	<li><img src="{% static 'img/adidas/5.png' %}" alt=""></li>
	<li><img src="{% static 'img/adidas/6.png' %}" alt=""></li>
	<li><img src="{% static 'img/adidas/1.png' %}" alt=""></li>
{% endblock rotation_picture %}
{% block main_shoestype %}
	<div id="adidas">
		<div id="harden">
			<h2>Harden系列</h2>
			<ul id="shoesList">
				<li class="harden1">
					<img src="{% static 'img/Harden/harden1-first.jpg' %}" id="harden1">
					<h3>Harden1</h3>
				</li>
				<li class="harden2">
					<img src="{% static 'img/Harden/harden2-first.jpg' %}" id="harden2">
					<h3>Harden2</h3>
				</li>
				<li class="harden">
					<img src="{% static 'img/Harden/harden3-first.jpg' %}" id="harden3">
					<h3>Harden3</h3>
				</li>
				<li class="harden">
					<img src="{% static 'img/Harden/harden4-first.jpg' %}" id="harden4">
					<h3>Harden4</h3>
				</li>
			</ul>
		</div>
	</div>
{% endblock main_shoestype %}
{% block js %}
	<script>
		window.onload = function() {
			// 查看更多
			function getMore(e) {
				var httprequest = new XMLHttpRequest();
				httprequest.onreadystatechange = handleResponse2;
				httprequest.open('GET',"http://127.0.0.1:8089/display/adidas/adidas_more");
				httprequest.send();		
			}
			more.onclick=getMore;
		};
	</script>
{% endblock js %}

display/templates/adidas/harden/harden1.html
{% extends 'theme_for_shoes_detail.html' %}
{% load staticfiles %}
{% block image %}
    <img src="{% static 'img/Harden/Harden1/1-1.jpg' %}">
    <img src="{% static 'img/Harden/Harden1/1-2.jpg' %}">
    <img src="{% static 'img/Harden/Harden1/1-3.jpg' %}">
    <img src="{% static 'img/Harden/Harden1/1-4.jpg' %}">
{% endblock image %}
       
{% block describe %}       
    <p>
        外观上这双球鞋，采用了分割的设计，前掌鞋面是一层皮革材质，而其他部分则是使用得当织物材质。颜值还算不错的，看着骚里骚气的，虽然图片看上去就那样，不过上脚感觉颜值还是跟得上的。
    </p>
    <p>
        包裹性及格分偏上，整体包裹性还算不错，在低帮的球鞋来看包裹性还是不错，不过纵向比较起来，包裹性也就那样。
    </p>
    <p>
        透气这一点只能给一个及格分了，毕竟鞋头部分是一层皮革材质，不过秋冬天还算穿着舒服，夏天喜欢着打球，那就不是很舒服了，闷脚感觉明显。
    </p>
    <p>
        不得不说boost是真的牛逼，上脚感觉是真的软弹，缓震是真的牛逼，抓地性不错，突破的时候很舒服，鞋底的纹路奇奇怪怪的，提供了不错的抓地性，抓地这块能有个八分吧。
    </p>
{% endblock describe %}

display/templates/adidas/harden/harden2.html
{% extends 'theme_for_shoes_detail.html' %}
{% load staticfiles %}
{% block image %}
    <img src="{% static 'img/Harden/Harden2/2-1.jpg' %}">
    <img src="{% static 'img/Harden/Harden2/2-2.jpg' %}">
    <img src="{% static 'img/Harden/Harden2/2-3.jpg' %}">
    <img src="{% static 'img/Harden/Harden2/2-4.jpg' %}">
{% endblock image %}
       
{% block describe %}
    <p>
        无论怎样幅度的动作对鞋身都很难造成夸张形变，这要归功于 adidas 在 Harden Vol.2 的鞋面上采用了 Forgefiber 的科技。这种将 TPU 涂层织物通过机器编程二次编织在鞋面上的技术可以使鞋面分区域的起到力度支撑的效果。
    </p>
    <p>
        说实话，作为一名经常打球的人，对缓震的要求怎么都不会轻谈满意。可 Harden Vol.2 已经搭载了adidas 招牌，也是现在缓震科技中最受推崇的缓震科技 BOOST 。
    </p>
    <p>
        作为一双加载了近全掌内靴的球鞋，保护性能似乎应该不成问题，实际上 Harden Vol.2 的内靴贴合度也十分争气。可问题是，哈登二的前掌相对较窄，而亚洲人较宽的脚型在买鞋时需要大半码选用，造成鞋子的保护性不能达到预期。
    </p>
    <p>
        在哈登二上，后跟非常夸张的上包，而所有后撤步的脚步，都是后跟先于前掌落地，这样的包围式后跟设计可以有效的保证球员稳定的完成出手。而嵌于中底和外底间的大面积 TPU 也有效保证了鞋底的抗扭转性。
    </p>
{% endblock describe %}

display/templates/adidas/harden/harden3.html
{% extends 'theme_for_shoes_detail.html' %}
{% load staticfiles %}
{% block image %}
    <img src="{% static 'img/Harden/Harden3/3-1.jpg' %}">
    <img src="{% static 'img/Harden/Harden3/3-2.jpg' %}">
    <img src="{% static 'img/Harden/Harden3/3-3.jpg' %}">
    <img src="{% static 'img/Harden/Harden3/3-4.jpg' %}">
{% endblock image %}
       
{% block describe %}
    <p>
        这一代的外观和之前一代完全不同，在构造上化繁为简，而看到实物时候觉得鞋子还是挺不错的，各方各面都把哈登元素表现的玲璃尽致，鞋舌处的哈登专属Logo，鞋头弹性绑带上的哈登签名字样，以及鞋子内侧的哈登的13号英文字样，表现的都非常直观。
    </p>
    <p>
        这一代的鞋帮比上一代有所降低，大大提高了灵活性，脚后跟的“大屁股”非常厚实，保护性还是不错的。整个鞋面部分最重要的就是位于前掌的这跟弹性绑带了，提高了鞋面的支撑。
    </p>
    <p>
        这一代的Boost厚度有所降低，很多朋友可能觉得“缩水”了，但是恰恰相反，厚度的降低并不会影响脚感，反而更实在了，缓震绝对够用，而整个鞋子的重心相对来说也低了，加上前掌外侧的稳定模块和弹性绑带是相关联的，反馈感稳定性得到了明显的提升。另一个要说的就是它的外底，大面积的人字纹大大提高了防滑耐磨性。
    </p>
{% endblock describe %}

display/templates/adidas/harden/harden4.html
{% extends 'theme_for_shoes_detail.html' %}
{% load staticfiles %}
{% block image %}
    <img src="{% static 'img/Harden/Harden4/4-1.jpg' %}">
    <img src="{% static 'img/Harden/Harden4/4-2.jpg' %}">
    <img src="{% static 'img/Harden/Harden4/4-3.jpg' %}">
    <img src="{% static 'img/Harden/Harden4/4-4.jpg' %}">
{% endblock image %}
       
{% block describe %}
    <p>
        首先从外观说起，哈登4整体外观上没有很大的槽点，视觉设计和新天足BYW如出一辙，分区域不同线条轮廓的设计，不仅有视觉上的细腻感受，也更加有利于赛场的实战性表现。
    </p>
    <p>
        Harden Vol. 4搭载了全新的轻质缓震科技——Lightstrike，这种材料制定轻盈，以酷似甲片的多面形态呈现，具有很强的缓震脚感以及能量反馈，
    </p>
    <p>
        整个鞋底的柔软程度介于Bounce和Boost之间，弹性和支撑性方面有着出色的平衡表现，相对来说更适合篮球运动，事实证明，Harden Vol. 4在实战中的表现也令人惊讶。
    </p>
{% endblock describe %}

info/templates/info.html
{% extends 'theme.html' %}
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
    <head>
        {% block css %}<link rel="stylesheet" href="{% static 'css/info.css' %}">{% endblock css %}
        {% block title %}<title>网站介绍</title>{% endblock title %}  
    </head>
    <body>
        {% block body %}
            <div id="topAnchor"></div>
            <header>
                <div class="header">
                    <div class="logo">
                        <h1>
                            <a href="{% static 'img/info/logo.png' %}"><img src="{% static 'img/index/logo.png' %}" alt="LOGO"></a>
                        </h1>
                    </div>
                    <div class='user'>
                        <!-- 若用户已登录 -->
                        {% if user.is_authenticated %}
                            <a href="{% url 'user:publish' %}">发布</a>&nbsp;&nbsp;&nbsp;
                            <a href="Javascript:{document.getElementById('logout').submit()}">退出</a>&nbsp;&nbsp;&nbsp;
                            <a href="{% url 'user:publish_list' %}">网友发布</a>
                            <form id="logout" method="POST" action="{% url 'user:logout' %}">
                                {% csrf_token %}
                                <input type="hidden">
                            </form> 
                        {% else %}
                            <a href="{% url 'user:login' %}">登录</a>&nbsp;&nbsp;&nbsp;
                            <a href="{% url 'user:signup' %}">注册</a>&nbsp;&nbsp;&nbsp;
                            <a href="{% url 'user:publish_list' %}">网友发布</a>
                        {% endif %}
                    </div>
                    <div class="navitems">
                        <a href="{% url 'info:info' %}" class="now show">网站介绍</a>
                        <div class="show" id="show">球鞋展示
                            <div class="frame1" id="frame">
                                <a href="{% url 'display:shoes_list' 'nike' %}">Nike</a>
                                <a href="{% url 'display:shoes_list' 'adidas' %}">Adidas</a>
                                <a href="{% url 'display:shoes_list' 'converse' %}">Converse</a>
                            </div>
                        </div>
                        <a href="{% url 'news:news' '1' %}" class="show">球鞋资讯</a>
                        <a href="{% url 'contact:contact' %}" class="show">联系我们</a>
                        <a href="{% url 'index:index' %}" class="show">回到首页</a>
                    </div>
                </div>
            </header>
            <main>
                <div class="main">
                    <div class="play">
                        <div id="wrap">
                            <img src="{% static 'img/info/a.png' %}" alt="" id="p01">
                            <img src="{% static 'img/info/b.png' %}" alt="" id="p02">
                            <img src="{% static 'img/info/c.png' %}" alt="" id="p03">
                            <img src="{% static 'img/info/d.png' %}" alt="" id="p04">
                            <img src="{% static 'img/info/e.png' %}" alt="" id="p05">
                            <img src="{% static 'img/info/f.png' %}" alt="" id="p06">
                        </div>
                        <h4>点击图片可播放动画</h4>
                    </div>
                    <div class="article">
                        <div class="article1">
                            <div class="title_left">
                                <h2>设计理念</h2>
                            </div>
                            <div class="content_left">
                                <br><br><br><br><br><br>
                                <p>&nbsp;&nbsp;&nbsp;更好的视觉展示</p>
                                <br><br><br><br><br><br>
                                <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;最实用球鞋信息</p>
                                <br><br><br><br><br><br>
                                <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;最新的球鞋资讯</p>
                            </div>
                            <img class="img_right" src="{% static 'img/info/1.jpg' %}" alt="图">
                        </div>
                        <div class="article2">
                            <img class="img_left" src="{% static 'img/info/2.jpg' %}" alt="图">
                            <div class="title_right">
                                <h2>适宜人群</h2>
                            </div>
                            <div class="content_right">
                                <br><br><br><br><br><br>
                                <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;适合各个年龄段</p>
                                <br><br><br><br><br><br>
                                <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;想了解各种球鞋的新闻资讯</p>
                                <br><br><br><br><br><br>
                                <p>&nbsp;&nbsp;&nbsp;&nbsp;想了解每款球鞋的版型与简介</p>
                            </div>
                        </div>
                        <div class="article3">
                            <div class="title_left">
                                <h2>网站内容</h2>
                            </div>
                            <div class="content_left">
                                <br><br><br><br><br><br>
                                <p>&nbsp;&nbsp;&nbsp;动画效果酷炫展示</p>
                                <br><br><br><br><br><br>
                                <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;球鞋的展示与介绍</p>
                                <br><br><br><br><br><br>
                                <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;各式球鞋实时资讯</p>
                            </div>
                            <img class="img_right" src="{% static 'img/info/3.jpg' %}" alt="图">
                        </div>
                        <div class="article4">
                            <img class="img_left" src="{% static 'img/info/4.jpg' %}" alt="图">
                            <div class="title_right">
                                <h2>网站目标</h2>
                            </div>
                            <div class="content_right">
                                <br><br><br><br><br><br>
                                <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;加入更多球鞋以供参考</p>
                                <br><br><br><br><br><br>
                                <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;实现球鞋资讯实时更新</p>
                                <br><br><br><br><br><br>
                                <p>&nbsp;&nbsp;&nbsp;&nbsp;联系我们的用户及时反馈</p>
                            </div>
                        </div>
                    </div>
                </div>
            </main>
            <footer>
                <div class="footer">
                    <a class="anchor" href="#topAnchor">回到顶部</a>
                </div>
            </footer>
            {% if messages %}
            {% for msg in messages %}
            <script>alert('{{ msg.message }}');</script>
            {% endfor %}
            {% endif %}
            <script src="{% static 'js/info.js' %}"></script>
        {% endblock body %}
    </body>
</html>

user/templates/login.html
{% extends 'theme_for_user.html' %}

{% block title %}<title>登录界面</title>{% endblock title %}
{% block psg_title %}<h2 class='title'>Login</h2>{% endblock psg_title %}
{% block user_main %}
<main>
    <div class="main">
        <div class="contact-section">
            <div class="border"></div>
            <form action="{% url 'user:login' %}" class="contact-form" method="POST">  
            <!-- 防止跨站点攻击 -->
            {% csrf_token %}
                <input type="text" name='username' class="contact-form-text" id="userName" placeholder="Please input your username">
                <input type="password" name='password' class="contact-form-text" id="password" placeholder="Please input your password">
                <div class='error'>{{ error }}</div>
                <input type="submit" class="contact-form-btn" value="Login">
            </form>
        </div>
    </div>
</main>
{% endblock user_main %}

user/templates/publish.html
{% extends 'theme_for_user.html' %}

{% block title %}<title>发布界面</title>{% endblock title %}
{% block psg_title %}<h2 class='title'>My Shoes</h2>{% endblock psg_title %}
{% block user_main %}
<main>
    <div class="main">
        <div class="contact-section">
            <div class="border"></div>
            <form action="{% url 'user:publish' %}" class="contact-form" method="POST" enctype='multipart/form-data'>
                {% csrf_token %}
                    <label for="shoes_title">Title</label>   
                    <input name="shoes_title" type="text" class="contact-form-text" id="shoes_title" placeholder="例：AJ1">
                
                    <label for="shoes_introduce">Introduce</label>
                    <textarea name="shoes_introduce" class="contact-form-text" id="shoes_introduce" placeholder="例：外表美观"></textarea>
                
                    <label for="shoes_small_picture">Shoes Small Picture</label>
                    <input type="file" name="shoes_small_picture" class="contact-form-file" id="shoes_small_picture" >
                   
                    <label for="shoes_big_picture">Shoes Big Picture</label>
                    <input type="file" name="shoes_big_picture" class="contact-form-file" id="shoes_big_picture" >
                    
                    <div class='error'>{{ picture_error }}</div>
                    <input type="submit" class="contact-form-btn" value="publish now">
            </form>
        </div>
    </div>
</main>

{% endblock user_main %}

user/templates/signup.html
{% extends 'theme_for_user.html' %}

{% block title %}<title>注册界面</title>{% endblock title %}
{% block psg_title %}<h2 class='title'>signup</h2>{% endblock psg_title %}
{% block user_main %}
<main>
    <div class="main">
        <div class="contact-section">
            <div class="border"></div>
            <form action="{% url 'user:signup' %}" class="contact-form" method="POST">  
            <!-- 防止跨站点攻击 -->
            {% csrf_token %}
                <input type="text" name='username' class="contact-form-text" id="userName" placeholder="Please input your username">
                <div class='error'>{{ username_error }}</div>
                <input type="password" name='password_initial' class="contact-form-text" id="password" placeholder="Please input your password">
                <input type="password" name='password_confirm' class="contact-form-text" id="password" placeholder="Please confirm your password">
                <div class='error'>{{ password_error }}</div>
                <input type="submit" class="contact-form-btn" value="Signup Now">
            </form>
        </div>
    </div>
</main>

{% endblock user_main %}